### ISSUE TITLE
`pluginSinceBuild` and `pluginUntilBuild` properties are unused

### ISSUE THREAD

**Issue by ForNeVeR** [jezzsantos/automate.plugin-rider#35]
In the `gradle.properties` of this plugin, there are the `pluginSinceBuild` and `pluginUntilBuild` properties:
https://github.com/jezzsantos/automate.plugin-rider/blob/1701ab76ae80ab3a0ba2122d3fe2eb330bc324fc/gradle.properties#L4-L5

I guess that they come from the [IntelliJ Platform Plugin Template](https://github.com/JetBrains/intellij-platform-plugin-template).

I've noticed that they are unused in this plugin. In the template, they are used in `build.gradle.kts`: https://github.com/JetBrains/intellij-platform-plugin-template/blob/61a1a04ede797d4c3a3a000e63eae3f0123ebfd3/build.gradle.kts#L70-L71

But in automate-plugin.rider, they are never used, and so the plugin gets default version dependencies (which start from the SDK version the plugin is built against, and end at the next major version).

This may be the reason your plugin isn't currently marked as compatible with Rider 2022.3.0 (since you are building against a SNAPSHOT SDK, as recommended in [RIDER-86051](https://youtrack.jetbrains.com/issue/RIDER-86051)):
<img width="752" alt="image" src="https://user-images.githubusercontent.com/92793/207568139-1e714aaa-108a-4a9d-94a4-3b1b954514be.png">

I would recommend to override `sinceBuild` and `untilBuild` in your `build.gradle`, similarly to how it's done in the template.

**Comment by jezzsantos** [comment]
Thank you heaps @ForNeVeR 

Yes, I had copied this pattern from another plugin (https://plugins.jetbrains.com/plugin/13984-application-insights-debug-log-viewer), and this is the first ever plugin I've had to build, so I'm not sure of how all the pieces hang together yet.
_(Gradle has been a steep-learning curve for me too. (not to mention Java, Groovy, etc))_
So I really appreciate you stepping in and giving your time to help me here.

Now updated the [build.gradle](https://github.com/jezzsantos/automate.plugin-rider/blob/main/build.gradle#L94). 
and [gradle.properties](https://github.com/jezzsantos/automate.plugin-rider/blob/main/gradle.properties)
Can you confirm what you see now is correct for this workaround?

**Comment by ForNeVeR** [comment]
> _(Gradle has been a steep-learning curve for me too. (not to mention Java, Groovy, etc))_

Believe me, we all have been there :)

The changes look correct to me.

One thing you can do to verify that yourself: open as `.zip` archive built by `gradlew buildPlugin`, find your `.jar` file inside of a `lib` directory, and find the `META-INF/plugin.xml` (so, the full path is like `automate-1.1.3.zip/automate/lib/automate-1.1.3.jar/META-INF/plugin.xml`).

It should contain a tag like `<idea-version since-build="222" until-build="231.*" />`: the version numbers should be taken from your `gradle.properties`.

I can see that an updated version is already uploaded onto the plugin Marketplace, and it looks like it has the right numbers.

**Comment by jezzsantos** [comment]
Thank you very much @ForNeVeR. It is so cool to have angels in this community.
