### ISSUE TITLE
Compatibility with JetBrains Rider 2023.3.2 Build #RD-233.13135.100

### ISSUE THREAD

**Issue by BigHoss** [jezzsantos/automate.plugin-rider#51]
when is the update available?

**Comment by jezzsantos** [comment]
Hey there @BigHoss 

Thanks for getting in touch. You would be the first to do that.

I see no reason not to support any future version of Rider.
Seems like we just need to publish a version with the magic symbols that make this happen.
Standby

**Comment by jezzsantos** [comment]
Hey @BigHoss you should find the 1.3.0 release in the marketplace as soon as JetBrains approves it. (usually a day or two from now)
