### ISSUE TITLE
Compatibility with JetBrains Rider 2024.2.6 Build #RD-242.23339.62

### ISSUE THREAD

**Issue by BigHoss** [jezzsantos/automate.plugin-rider#52]
same issue as before.

the tool is amazing but so tiresome to use in the CLI

**Comment by jezzsantos** [comment]
Thanks @BigHoss 

Sorry for the inconvience.
I went to upgrade the version today, but am blocked having to upgrade a bunch of other dependencies, like gradle and things.

Will resolve with JetBrains ASAP, and publish a new version for you.

Sorry about this, you are in fact the only one letting me know the tool is amazing so thanks for that.
I will try to stay on top of it for you.
(have moved focus over to [SaaStack](https://github.com/jezzsantos/saastack))

**Comment by jezzsantos** [comment]
Hey there @BigHoss new release it out 1.4.0. Works for versions up to 2024.1.

I'm working on a version for > 2024.1, but much to change. Will be there soon.

**Comment by jezzsantos** [comment]
There is now a version available for Rider 2024.1 onwards. v1.5.0
